In [586]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [587]:
df=pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [588]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [589]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [590]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [591]:
df.shape

(7043, 21)

In [592]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [593]:
df.duplicated().sum()

np.int64(0)

In [594]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [595]:
df['MultipleLines'].value_counts()

MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

In [596]:
df['customerID'].value_counts()

customerID
7590-VHVEG    1
3791-LGQCY    1
6008-NAIXK    1
5956-YHHRX    1
5365-LLFYV    1
             ..
9796-MVYXX    1
2637-FKFSY    1
1552-AAGRX    1
4304-TSPVK    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64

In [597]:
# df['customerID']=le.fit_transform(df['customerID'])
# df['MultipleLines']=le.fit_transform(df['MultipleLines'])
# df['InternetService']=le.fit_transform(df['InternetService'])
# df['Contract']=le.fit_transform(df['Contract'])
# df['PaymentMethod']=le.fit_transform(df['PaymentMethod'])
# df['gender']=le.fit_transform(df['gender'])
# df['PaymentMethod']=le.fit_transform(df['PaymentMethod'])
# df['PaymentMethod']=le.fit_transform(df['PaymentMethod'])

In [598]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [599]:
cat_features=['gender','Partner','Dependents','PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod','Churn']

In [600]:
df = df.drop("customerID", axis=1)

In [601]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}

for col in cat_features:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [602]:
df['TotalCharges'].dtype

dtype('O')

In [603]:
# Convert TotalCharges to numeric, forcing errors to NaN
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [604]:
df['TotalCharges'].isnull().sum()

np.int64(11)

In [605]:
df['TotalCharges'] = df['TotalCharges'].fillna(0)

In [606]:
df = df.astype(int)
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29,29,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56,1889,0
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53,108,1
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42,1840,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70,151,1

In [607]:
# df = df.drop("customerID", axis=1)

In [608]:
X=df.drop('Churn',axis=1)
y=df['Churn']

In [609]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

LOGISTIC REGRESSION-

In [610]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [611]:
y_pred=model.predict(X_test)

In [612]:
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report

In [613]:
accuracy_score(y_test,y_pred)

0.815471965933286

In [614]:
confusion_matrix(y_test,y_pred)

array([[934, 102],
       [158, 215]])

In [615]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.86      0.90      0.88      1036
           1       0.68      0.58      0.62       373

    accuracy                           0.82      1409
   macro avg       0.77      0.74      0.75      1409
weighted avg       0.81      0.82      0.81      1409

In [616]:
from sklearn.metrics import roc_auc_score

y_prob = model.predict_proba(X_test)[:, 1]
roc_auc = roc_auc_score(y_test, y_prob)

print("ROC-AUC:", roc_auc)

ROC-AUC: 0.8580214166675293

KNN-

In [617]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [618]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [619]:
from sklearn.neighbors import KNeighborsClassifier

In [620]:
knn_model=KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [621]:
y_pred_knn=knn_model.predict(X_test_scaled)

In [622]:
confusion_matrix(y_test,y_pred_knn)

array([[882, 154],
       [193, 180]])

In [623]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.82      0.85      0.84      1036
           1       0.54      0.48      0.51       373

    accuracy                           0.75      1409
   macro avg       0.68      0.67      0.67      1409
weighted avg       0.75      0.75      0.75      1409

In [624]:
from sklearn.metrics import roc_auc_score

y_prob_knn = knn_model.predict_proba(X_test)[:, 1]
roc_auc = roc_auc_score(y_test, y_prob_knn)

print("ROC-AUC:", roc_auc)

ROC-AUC: 0.4897600587949113

DECISION TREEE-

In [625]:
from sklearn.tree import DecisionTreeClassifier

In [626]:
model_DT=DecisionTreeClassifier(random_state=42)

In [627]:
model_DT.fit(X_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [628]:
y_pred_DT=model_DT.predict(X_test_scaled)

In [629]:
y_pred_DT

array([0, 0, 0, ..., 1, 0, 1], shape=(1409,))

In [630]:
confusion_matrix(y_test,y_pred_DT)

array([[866, 170],
       [224, 149]])

In [631]:
print(classification_report(y_test,y_pred_DT))

              precision    recall  f1-score   support

           0       0.79      0.84      0.81      1036
           1       0.47      0.40      0.43       373

    accuracy                           0.72      1409
   macro avg       0.63      0.62      0.62      1409
weighted avg       0.71      0.72      0.71      1409

In [632]:
from sklearn.metrics import roc_auc_score

y_prob_DT = model_DT.predict_proba(X_test)[:, 1]
roc_auc = roc_auc_score(y_test, y_prob_DT)

print("ROC-AUC:", roc_auc)

ROC-AUC: 0.737617356920306

RANDOM FOREST CLASSIFIER-

In [633]:
from sklearn.ensemble import RandomForestClassifier

In [634]:
rf_model=RandomForestClassifier(
    n_estimators=100,            #number of trees
    max_depth=None,              #let trees grow fully
    random_state=42
)

In [635]:
rf_model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [636]:
y_pred_rf=rf_model.predict(X_test)

In [637]:
print(classification_report(y_test,y_pred_rf))

              precision    recall  f1-score   support

           0       0.82      0.91      0.86      1036
           1       0.64      0.46      0.54       373

    accuracy                           0.79      1409
   macro avg       0.73      0.68      0.70      1409
weighted avg       0.78      0.79      0.78      1409

In [638]:
from sklearn.metrics import roc_auc_score

y_prob_rf = rf_model.predict_proba(X_test)[:, 1]
roc_auc = roc_auc_score(y_test, y_prob_rf)

print("ROC-AUC:", roc_auc)

ROC-AUC: 0.8358102932499716

GRADIENT BOOSTING-

In [639]:
from sklearn.ensemble import GradientBoostingClassifier

In [640]:
gb_model=GradientBoostingClassifier(n_estimators=100,learning_rate=0.1,random_state=42)

In [641]:
gb_model.fit(X_train,y_train)

GradientBoostingClassifier(random_state=42)

In [642]:
y_pred_gb=gb_model.predict(X_test)

In [643]:
print(classification_report(y_test,y_pred_gb))

              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1036
           1       0.66      0.53      0.59       373

    accuracy                           0.80      1409
   macro avg       0.75      0.71      0.73      1409
weighted avg       0.79      0.80      0.80      1409

In [644]:
from sklearn.metrics import roc_auc_score

y_prob_gb = gb_model.predict_proba(X_test)[:, 1]
roc_auc = roc_auc_score(y_test, y_prob_gb)

print("ROC-AUC:", roc_auc)

ROC-AUC: 0.8580033020381546

XG BOOSTING -

In [645]:
from xgboost import XGBClassifier

In [646]:
xgb_model=XGBClassifier(n_estimators=100, learning_rate=0.1,max_depth=3,use_label_encoder=False,eval_metric='mlogloss',random_state=42)

In [647]:
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

In [648]:
xgb_model.fit(X_train, y_train_encoded)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [649]:
y_pred_xgb = xgb_model.predict(X_test)

In [650]:
print(classification_report(y_test_encoded,y_pred_xgb))

              precision    recall  f1-score   support

           0       0.84      0.91      0.88      1036
           1       0.68      0.53      0.60       373

    accuracy                           0.81      1409
   macro avg       0.76      0.72      0.74      1409
weighted avg       0.80      0.81      0.80      1409

In [651]:
from sklearn.metrics import roc_auc_score

y_prob_xgb = xgb_model.predict_proba(X_test)[:, 1]
# y_pred_xgb = (y_prob_xgb >= 0.40).astype(int)
roc_auc = roc_auc_score(y_test, y_prob_xgb)

print("ROC-AUC:", roc_auc)

ROC-AUC: 0.8584704006956018

USING GRID SEARCH CV

In [652]:
from sklearn.model_selection import GridSearchCV

In [653]:
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}

In [654]:
grid = GridSearchCV(
    estimator=xgb_model,
    param_grid=param_grid,
    cv=5,
    scoring='roc_auc',
    n_jobs=-1,
    verbose=1
)

grid.fit(X_train, y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=True,
                                     eval_metric='mlogloss', feature_types=None,
                                     feature_weights=None, gamma=None,
                                     grow_policy=None, importance_type=None,
                                     interaction_constraint...
                                     max_delta_step=None, max_depth=3,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=100,
                                     n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'colsample_bytree': [0.8, 1.0],
                         'learning_rate': [0.01, 0.1, 0.2],
                         'max_depth': [3, 5, 7], 'n_estimators': [100, 200],
                         'subsample': [0.8, 1.0]},
             scoring='roc_auc', verbose=1)

In [655]:
results=pd.DataFrame(grid.cv_results_)

In [656]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_colsample_bytree,param_learning_rate,param_max_depth,param_n_estimators,param_subsample,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.677694,0.016356,0.099437,0.002499,0.8,0.01,3,100,0.8,"{'colsample_bytree': 0.8, 'learning_rate': 0.0...",0.853328,0.837496,0.835466,0.826100,0.838737,0.838225,0.008758,27
1,0.504142,0.004623,0.093546,0.005785,0.8,0.01,3,100,1.0,"{'colsample_bytree': 0.8, 'learning_rate': 0.0...",0.852223,0.837730,0.834493,0.824051,0.835902,0.836880,0.009026,33
2,1.175883,0.030075,0.082491,0.005462,0.8,0.01,3,200,0.8,"{'colsample_bytree': 0.8, 'learning_rate': 0.0...",0.858496,0.843032,0.837304,0.829750,0.842868,0.842290,0.009441,9
3,0.882686,0.010570,0.078939,0.004373,0.8,0.01,3,200,1.0,"{'colsample_bytree': 0.8, 'learning_rate': 0.0...",0.857336,0.843147,0.836601,0.827983,0.840344,0.841082,0.009599,15
4,0.864425,0.033015,0.085264,0.006305,0.8,0.01,5,100,0.8,"{'colsample_bytree': 0.8, 'learning_rate': 0.0...",0.859364,0.840826,0.836543,0.834077,0.843450,0.842852,0.008876,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,1.115120,0.018457,0.092346,0.004708,1.0,0.20,5,200,1.0,"{'colsample_bytree': 1.0, 'learning_rate': 0.2...",0.841276,0.811231,0.811859,0.810645,0.808261,0.816654,0.012371,61
68,1.143969,0.057662,0.097012,0.014296,1.0,0.20,7,100,0.8,"{'colsample_bytree': 1.0, 'learning_rate': 0.2...",0.829506,0.804639,0.799531,0.802862,0.810790,0.809466,0.010668,69
69,0.979011,0.043688,0.086696,0.008984,1.0,0.20,7,100,1.0,"{'colsample_bytree': 1.0, 'learning_rate': 0.2...",0.841491,0.806008,0.808676,0.810852,0.813647,0.816135,0.012924,62
70,1.863331,0.078971,0.078159,0.015840,1.0,0.20,7,200,0.8,"{'colsample_bytree': 1.0, 'learning_rate': 0.2...",0.822825,0.800894,0.789364,0.791773,0.798472,0.800666,0.011855,72
71,1.264079,0.046126,0.049990,0.003556,1.0,0.20,7,200,1.0,"{'colsample_bytree': 1.0, 'learning_rate': 0.2...",0.830445,0.800640,0.799717,0.800879,0.804479,0.807232,0.011719,70

In [657]:
results[['param_colsample_bytree','param_learning_rate','param_max_depth','param_n_estimators','param_subsample','mean_test_score']]

,param_colsample_bytree,param_learning_rate,param_max_depth,param_n_estimators,param_subsample,mean_test_score
0,0.8,0.01,3,100,0.8,0.838225
1,0.8,0.01,3,100,1.0,0.836880
2,0.8,0.01,3,200,0.8,0.842290
3,0.8,0.01,3,200,1.0,0.841082
4,0.8,0.01,5,100,0.8,0.842852
...,...,...,...,...,...,...
67,1.0,0.20,5,200,1.0,0.816654
68,1.0,0.20,7,100,0.8,0.809466
69,1.0,0.20,7,100,1.0,0.816135
70,1.0,0.20,7,200,0.8,0.800666
71,1.0,0.20,7,200,1.0,0.807232

In [658]:
print("Best Parameters:", grid.best_params_)
print("Best CV ROC-AUC:", grid.best_score_)

Best Parameters: {'colsample_bytree': 1.0, 'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 100, 'subsample': 0.8}
Best CV ROC-AUC: 0.8442382773515732

In [659]:
best_xgb = grid.best_estimator_

In [660]:
y_pred_xgb_tuned = best_xgb.predict(X_test)
y_prob_xgb_tuned = best_xgb.predict_proba(X_test)[:, 1]

print(classification_report(y_test_encoded, y_pred_xgb_tuned))
print("ROC-AUC:", roc_auc_score(y_test_encoded, y_prob_xgb_tuned))

              precision    recall  f1-score   support

           0       0.85      0.91      0.88      1036
           1       0.68      0.55      0.61       373

    accuracy                           0.81      1409
   macro avg       0.76      0.73      0.74      1409
weighted avg       0.80      0.81      0.80      1409

ROC-AUC: 0.8602896270456593

In [661]:
import joblib

joblib.dump(best_xgb, "xgb_model.pkl")
joblib.dump(label_encoders, "label_encoders.pkl")

['label_encoders.pkl']